# Ruff configuration
line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "W"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
