[project]
name = "kokoro-onnx1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kokoro-onnx[gpu]>=0.3.6",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
]
